# Generated by Django 4.2.29 on 2026-03-08 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Medication name (brand or generic)', max_length=200)),
                ('generic_name', models.CharField(blank=True, help_text='Generic name if applicable', max_length=200)),
                ('dosage', models.CharField(help_text='Dosage (e.g., 10mg, 5ml)', max_length=100)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('LIQUID', 'Liquid'), ('INJECTION', 'Injection'), ('INHALER', 'Inhaler'), ('CREAM', 'Cream/Ointment'), ('DROPS', 'Drops'), ('PATCH', 'Patch'), ('OTHER', 'Other')], default='TABLET', help_text='Form of medication', max_length=20)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once daily'), ('TWICE', 'Twice daily'), ('THRICE', 'Three times daily'), ('FOUR', 'Four times daily'), ('EVERY_OTHER', 'Every other day'), ('WEEKLY', 'Once weekly'), ('BIWEEKLY', 'Twice weekly'), ('MONTHLY', 'Once monthly'), ('AS_NEEDED', 'As needed'), ('SPECIFIC', 'Specific times'), ('OTHER', 'Other')], help_text='How often to take', max_length=20)),
                ('frequency_other', models.CharField(blank=True, help_text="If frequency is 'OTHER', specify here", max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('INHALATION', 'Inhalation'), ('INJECTION', 'Injection'), ('SUBLINGUAL', 'Sublingual'), ('RECTAL', 'Rectal'), ('OPHTHALMIC', 'Ophthalmic'), ('OTIC', 'Otic'), ('OTHER', 'Other')], default='ORAL', help_text='Route of administration', max_length=20)),
                ('prescribed_date', models.DateField(help_text='Date medication was prescribed')),
                ('start_date', models.DateField(help_text='Date to start taking medication')),
                ('end_date', models.DateField(blank=True, help_text='Date to stop taking medication (if applicable)', null=True)),
                ('specific_times', models.JSONField(blank=True, default=list, help_text="List of specific times for medication (e.g., ['09:00', '21:00'])")),
                ('prescribed_by', models.CharField(blank=True, help_text='Doctor who prescribed this medication', max_length=200)),
                ('prescription_number', models.CharField(blank=True, help_text='Prescription number', max_length=100)),
                ('pharmacy_name', models.CharField(blank=True, help_text='Pharmacy where medication was filled', max_length=200)),
                ('pharmacy_phone', models.CharField(blank=True, help_text='Pharmacy phone number', max_length=20)),
                ('refills_remaining', models.PositiveIntegerField(default=0, help_text='Number of refills remaining')),
                ('quantity', models.PositiveIntegerField(blank=True, help_text='Total quantity prescribed', null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions (take with food, etc.)')),
                ('reason', models.CharField(blank=True, help_text='Reason for taking this medication', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='ACTIVE', help_text='Current status of medication', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(help_text='Time to take medication')),
                ('dosage', models.CharField(help_text='Dosage for this specific time', max_length=100)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of days to take (0=Monday to 6=Sunday)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medication.medication')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(help_text='When to send reminder')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When reminder was sent', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.medication')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='medication.medicationschedule')),
            ],
            options={
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField(help_text='When the medication was supposed to be taken')),
                ('taken_at', models.DateTimeField(blank=True, help_text='When medication was actually taken', null=True)),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('LATE', 'Late')], default='MISSED', max_length=10)),
                ('dosage_taken', models.CharField(blank=True, help_text='Actual dosage taken (if different)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='medication.medication')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes', to='medication.medicationschedule')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('SIDE_EFFECT', 'Side Effect'), ('EFFECTIVENESS', 'Effectiveness'), ('NOTE', 'General Note'), ('QUESTION', 'Question for Doctor'), ('CONCERN', 'Concern')], default='NOTE', max_length=20)),
                ('content', models.TextField(help_text='Comment content')),
                ('severity', models.IntegerField(blank=True, help_text='Severity rating (1-10) for side effects', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('effectiveness', models.IntegerField(blank=True, help_text='Effectiveness rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='medication.medicationintake')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medication.medication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
