# Generated by Django 4.2.29 on 2026-03-08 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(help_text='Patient taking this medication', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='medicationschedule',
            unique_together={('medication', 'scheduled_time')},
        ),
        migrations.AddIndex(
            model_name='medicationintake',
            index=models.Index(fields=['medication', 'scheduled_time'], name='medication__medicat_6d7374_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationintake',
            index=models.Index(fields=['status'], name='medication__status_905cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient', 'status'], name='medication__patient_1a594e_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['start_date'], name='medication__start_d_e3c503_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['name'], name='medication__name_46144f_idx'),
        ),
    ]
