# Generated by Django 4.2.29 on 2026-04-04 13:27

from django.db import migrations, models
from django.utils import timezone
from medication.models import MedicationIntake
# Mark all future 'MISSED' records as 'PENDING'
MedicationIntake.objects.filter(status='MISSED', scheduled_time__gte=timezone.now()).update(status='PENDING')

class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationintake',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('SKIPPED', 'Skipped'), ('LATE', 'Late')], default='PENDING', max_length=10),
        ),
    ]
