# Generated by Django 4.2.29 on 2026-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_alter_medicationintake_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_alerted',
            field=models.BooleanField(default=False, help_text=' Tracks if the browser popup/sound has already been triggered'),
        ),
        migrations.AlterField(
            model_name='medicationintake',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('MISSED', 'Missed'), ('LATE', 'Late')], default='PENDING', max_length=10),
        ),
    ]
