# Generated by Django 4.2.29 on 2026-04-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_medicationnotification_alter_medicationintake_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationnotification',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationnotification',
            name='custom_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicationnotification',
            name='notification_type',
            field=models.CharField(choices=[('dose', 'Dose'), ('warning', 'Warning'), ('info', 'Info')], default='dose', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicationnotification',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medication.medication'),
        ),
    ]
